### ISSUE TITLE
Can I help?

### ISSUE THREAD

**Issue by pedrorgirardi** [xlm-sg/clj-stellar-sdk#1]
Hi Isaac, I started working on a Clojure/ClojureScript client for the Horizon API too. Maybe we could collaborate our efforts.
How is it going with the development?

**Comment by superstructor** [comment]
Hi Pedro, Sorry I didn't see your message earlier. At first, I am just attempting to wrap the Java and JavaScript SDKs. At least until there is feature parity with existing SDKs, I thought working out the best Clojure(Script) APIs and interfaces is more important than having a completely independent implementation. So far I have examples of loading balances and doing a native asset (XLM) transaction working in the REPL. Any help is appreciated if your still interested ?

**Comment by pedrorgirardi** [comment]
Very sorry @superstructor, I didn't see this. I was helping a startup here in Cambodia and they were interested in Stellar but a few things changed and they took another path.

Thank you very much for answering! I will close this. :)
